const ERROR_STATUS_CODE = {
  SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INVALID: 401,
  DUPLICATE: 409,
  FORBIDDEN: 403,
};
const SUCCESS_STATUS_CODE = {
  CREATED: 201,
  SUCCESS: 200,
};
const ERROR_MESSAGE = {
  PATIENT_ID_NOT_EXIST:"Patient ID does not exist or is already deleted.",
  APPOINTMENT_BOOKED:'Appointment is booked for this patient, so you cannot delete',
  LOGIN_CREDENTIAL:"Either email or userCode must be provided",
  KEYWORD_REQUIRED:"Keyword is required for searching",
  DOCTOR_NOT_AVAILABLE: "Doctor not available for the selected date or time.",
  BOOK_SLOT: "The selected time slot is already booked. Please choose another time.",
  EMAIL_NOT_EXISTS: "Email is not found",
  MORE_THAN_LIMIT: "Only 4 documents allow to upload",
  ID_ALREADY_EXISTS: "Patient_id already exists",
  CANNOT_DELETE: "Cannot delete the last admin user",
  USER_NOT_FOUND: "User not found",
  SERVER_ERROR_MESSAGE: "Internal Server Error",
  INVALID_TOKEN_MESSAGE: "Invalid token.",
  INVALID_USER_MESSAGE: "Invalid user",
  FORBIDDEN_ERROR_MESSAGE: "Failed to authenticate token",
  UNAUTHORIZED_ACCESS_MESSAGE: "Only admin can access this functionality",
  NOT_UPDATE_MESSAGE: "Failed to update information",
  NOT_DELETE_MESSAGE: "Failed to delete information",
  NO_FILE: "No file uploaded",
  MISSING_REQUIRED: "Missing required fields",
  ALREADY_REGISTER: "User already exists",
  DISEASE_STEP: "Please fill disease info first.",
  FAMILY_STEP: "Please fill family info next.",
  PERSONAL_INFO_EXISTS: "Personal information is already exist, if you want to change then update the information",
  FAMILY_INFO_EXISTS: "Family information is already exists, if you want to change then update the information",
  DISEASE_INFO_EXISTS: "Disease information is already exists, if you want to change then update the information",
  FORBIDDEN_MESSAGE: "Unauthorized access",
  DOCUMENT_NOT_FOUND: "Document not found",
  ADMIN_ACCESS: "Only an admin can add a user as a doctor.",
  DOCTOR_NOT_FOUND: "Doctor information is not found",
  NOT_CHANGE_STATUS: "Failed to change status",
  INVALID_INPUT: "Invalid Input",
  NOT_AVAILABLE: "Time slot is not available",
  LOGIN_FAILED: "Failed to login",
  FAILED_TO_RETRIVE: "Failed to retrieve data",
  CANNOT_DELETE_SUPERADMIN:"Cannot delete the superadmin",
  CANNOT_ADD_DOCTOR:"User not found. Please register the user before adding as a doctor.",
  FAILED_TO_CANCEL:"Failed to cancelled appointment",
  WRONG_PASSWORD:"Please enter a correct old password",
  PRESCRIPTION_NOT_EXISTS:"Prescription not uploaded by the doctor. Status cannot be marked as completed."
};

const SUCCESS_MESSAGE = {
  CHANGE_DOCTOR_STATUS:"Change doctor Availability Status Successfully",
  PATIENT_COUNT_SUCCESS_MESSAGE:"Patient age wise count retrieve successfully",
  DOCTOR_INFO_SUCCESS_MESSAGE:"Doctor information retrieve successfully",
  APPOINTMENT_CANCELLED:"Appointment is cancelled successfully",
  DOCTOR_PROFILE:"Doctor profile retrived successfully",
  EMAIL_RETRIVE:"Retrieve all emails successfully",
  ALL_APPOINTMENTS: "Retrive all appointments information successfully",
  REQUESTED_APPOINTMENT: "Requested appointments retreived successfully",
  PRESCRIPTION_UPLOAD: "Prescription uploaded successfully",
  BOOKED_APPOINTMENTS: "Scheduled appointments data display successfully",
  CHANGE_STATUS: "Appointments status change successfully",
  SCHEDULED_APPOINTMENTS: "Scheduled appointments is retrived successfully",
  AVAILABLE_SLOT: "Available slot is retrieved successfully",
  APPOINTMENT_BOOKED: "Appointment request send successfully",
  UPDATED_DOCTOR_INFO_MESSAGE: "Doctor details updated successfully",
  ADDED_DOCTOR_INFO_MESSAGE: "Doctor information added successfully",
  OTP_SENT: "OTP is sent to your email",
  USER_DELETED: "This user is deleted, if you want login then signup the user",
  ADD_ADMIN: "Set as a admin successfully",
  DOCUMENT_DELETED: "Document deleted successfully",
  REMOVE_ADMIN: "Remove as a admin successfully",
  ADMIN_LOGIN: "Admin login",
  LOGIN_SUCCESS_MESSAGE: "Login successfully",
  USER_UPDATE_SUCCESS_MSG: "User credentials updated successfully",
  RETRIEVE_INFO_SUCCESS_MESSAGE: "Patient details are retrieved successfully",
  ADDED_PERSONAL_INFO_MESSAGE: "Personal information added successfully",
  UPDATE_INFO_SUCCESS_MESSAGE: "Information updated successfully",
  DELETE_SUCCESS_MESSAGE: "Information deleted successfully",
  ADDED_FAMILY_MESSAGE: "Family information added successfully",
  GET_FAMILY_INFO_MESSAGE: "Family information retrieved successfully",
  DISEASE_DETAILS: "Disease details retrieved successfully",
  CREATED_DISEASE_INFO_MESSAGE: "Disease information added successfully",
  DOCUMENT_UPLOAD: "Document uploaded successfully",
  REGISTER_SUCCESS: "User registered successfully. Verification email sent.",
  PERSONAL_UPDATE: "Personal information updated successfully",
  FAMILY_UPDATE_SUCCESSFULLY: "Family information updated successfully",
  FAMILY_DELETE_SUCCESSFULLY: "Family information deleted successfully",
  DISEASE_UPDATE_SUCCESSFULLY: "Disease information updated successfully",
  DISEASE_DELETE_SUCCESSFULLY: "Disease information deleted successfully",
  DOCUMENT_UPDATE_SUCCESSFULLY: "Document updated successfully",
  DOCUMENT_DELETE_SUCCESSFULLY: "Document deleted successfully",
  GET_ADMIN: "Admin are retrieve successfully",
  ADMIN_ACCESS: "Only admin can access",
  PASSWORD_UPDATE: "Password is updated successfully",
  USER_INFO_SUCCESS_MESSAGE: "User details retrieve successfully"
};

export {
  ERROR_STATUS_CODE,
  SUCCESS_STATUS_CODE,
  ERROR_MESSAGE,
  SUCCESS_MESSAGE,
};
